# Generated by Django 5.1.3 on 2024-11-21 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_profile_birth_date_profile_interests_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('image', 'Фото'), ('video', 'Видео')], max_length=10)),
                ('file', models.FileField(upload_to='profile_media/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='profiles.profile')),
            ],
        ),
    ]
